# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

archives_base_name=advancements_reloaded
modrinth_id=tLuRLqpa
curseforge_id=1113876

mod_version=0.15.0
releaseType=beta
maven_group = codes.atomys.advr

minecraft_version=26.3
# used only as display for players
supported_minecraft_versions=26.3
# used in the version creation process (.split(","))
supported_minecraft_versions_list=26.3
# which platforms are supported by the mod
platforms=fabric,neoforge

# https://fabricmc.net/develop/
fabric_loader_version=0.19.5
fabric_api_version=0.161.0+26.3

# https://modrinth.com/mod/cloth-config/versions
cloth_version=26.3.159
# https://modrinth.com/mod/modmenu/versions
modmenu_version=21.0.0
# https://neoforged.net
neoforge_version=26.3.0.43-beta
