# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

archives_base_name=advancements_reloaded
modrinth_id=tLuRLqpa
curseforge_id=1113876

mod_version=0.14.0
releaseType=beta
maven_group = codes.atomys.advr

minecraft_version=26.2
# used only as display for players
supported_minecraft_versions=26.2
# used in the version creation process (.split(","))
supported_minecraft_versions_list=26.1,26.1.1,26.1.2,26.2
# which platforms are supported by the mod
platforms=fabric,neoforge

# https://fabricmc.net/develop/
fabric_loader_version=0.19.3
fabric_api_version=0.152.2+26.2

# https://modrinth.com/mod/cloth-config/versions
cloth_version=26.2.155
# https://modrinth.com/mod/modmenu/versions
modmenu_version=20.0.0-beta.3
# https://neoforged.net
neoforge_version=26.2.0.6-beta
